In [348]:
# Importing numpy
import numpy as np

In [349]:

# Introducing NumPy Arrays


In [350]:
# Simple array creation
a = np.array([0,1,2,3,4])

In [351]:
# Cheking the type
type(a)

numpy.ndarray

In [352]:
# Numeric 'type' of elements
a.dtype

dtype('int64')

In [353]:
# Number of dimentions
a.ndim

1

In [354]:
# Array shape
#  Shape returns a tuple
# listing the length of the
# array along each dimension.

a.shape

(5,)

In [355]:
# Get the number of elements in the array
a.size

5

In [356]:
# Bytes per elements.
a.itemsize

8

In [357]:
# Bytes of memory used
# Return the number of bytes
# used by the data portion of
# the array.

# a has 5 items each takes 8 bytes -> 40.

a.nbytes

40

In [358]:

# Array Operations


In [359]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [360]:
# Addition
a + b

array([3, 5, 7, 9])

In [361]:
# Subtraction
a - b

array([-1, -1, -1, -1])

In [362]:
# Multiplication
a * b

array([ 2,  6, 12, 20])

In [363]:
# Division
a / b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [364]:
# Power
a ** b

array([   1,    8,   81, 1024])

In [365]:
 # Math functions

In [366]:
# create array from 0. to 10.
x = np.arange(11.)

In [367]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [368]:
# multiply entire array by 
# scalar value
c = (2 * np.pi) / 10.

In [369]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [370]:
# in-place operations
x *= c

In [371]:
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [372]:
# apply functions to array
np.sin(x)

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

In [373]:
# Setting Array Elements.

In [374]:
# Array indexing
a[0]

1

In [375]:
a

array([1, 2, 3, 4])

In [376]:
# assigning a float into
# an int32 array truncates
# the decimal part
a[0] = 10.6

In [377]:
a

array([10,  2,  3,  4])

In [378]:
# fill has the same behavior
a.fill(-4.8)

In [379]:
a

array([-4, -4, -4, -4])

In [380]:
# Multi-Dimentional Arrays 

In [381]:
arr_2d = np.array([[0,1,2,3], [10,11,12,14]])

In [382]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 14]])

In [383]:
arr_2d.shape

(2, 4)

In [384]:
 # Element count
arr_2d.size

8

In [385]:
# Number of dimentions
arr_2d.ndim

2

In [386]:
# Get, Set Elements
arr_2d[0, 0] # get the first item of the first array

0

In [387]:
arr_2d[1,2] # get the third item of the second array
# NOTE : Numpy has 0 indexed arrays.

12

In [388]:
arr_2d[1, 3] = -1

In [389]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [390]:
arr_2d[1] # Get all the elements of the second array

array([10, 11, 12, -1])

In [391]:

# Indexing and Slicing


In [392]:
# Slicing
# var[lower:upper:step]
a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [393]:
a[1:-2] # Negative indices work also

array([11, 12])

In [394]:
a[-4:3]

array([11, 12])

In [395]:
# omitted boundaries are
# assumed to be the beginning
# (or end) of the list

In [396]:
a[:3] # Grab first 3 elements

array([10, 11, 12])

In [397]:
a[-2:] # Grab last 2 elements

array([13, 14])

In [398]:
a[::2] # every other element

array([10, 12, 14])

In [399]:
# Array Slicin'
# Slicing works much like
# standard python slicing.

In [400]:
a = np.array([
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
])
a[0,3:5] # First row column 3->5 (5 not included.)

array([3, 4])

In [401]:
a[2:, 4:] # Get all rows starting from row 2 and all columns starting
          # from the fourth column

array([[24, 25],
       [34, 35],
       [44, 45]])

In [402]:
a[:, 2] # All rows of column number 2.

array([ 2, 12, 22, 32, 42])

In [403]:
a[2::2, ::2] # Strided are also possible

array([[20, 22, 24],
       [40, 42, 44]])

In [404]:
# Slices are references to locations in memory
# These memory locations can be used in assignment operations.

In [405]:
a = np.array([0, 1, 2, 3, 4])
# slicing the last two elements returns the data there
a[-2:]
a

array([0, 1, 2, 3, 4])

In [406]:
  # we can insert an iterable of length two
a[-2:] = [-10, -20] # This is valid if they have the same length.
a

array([  0,   1,   2, -10, -20])

In [407]:
# or a scalar value
a[-2:] = 99
a

array([ 0,  1,  2, 99, 99])

In [408]:
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [409]:
c[-1]# get last row

array([20, 21, 22, 23, 24])

In [410]:
c[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [411]:
c[1::2, :-1:2]

array([[ 5,  7],
       [15, 17]])

In [412]:
# If you wanna make a copy use copy()
d = c.copy()
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [413]:
d [0, 1] = -10
d

array([[  0, -10,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [414]:
c # C is unchanged.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [415]:
# Fancy Indexing

In [416]:
# Indexing by position.
a = np.arange(0, 80, 10)

In [417]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [418]:
y = a[[1,2,-3]] # Fancy indexing.

In [419]:
y

array([10, 20, 50])

In [420]:
# This also work with setting.
a[[1,2,-3]] = 90

In [421]:
a

array([ 0, 90, 90, 30, 40, 90, 60, 70])

In [422]:
# Indexing by booleans
mask = np.array([1,0,1,0,0,0,1,0], dtype=bool)

In [423]:
y = a[mask]# Fancy Indexing 

In [424]:
y

array([ 0, 90, 60])

In [425]:
neg_pos = np.array([0,1,-1,-3,-2,4,6,-9])

In [426]:
negative = neg_pos < 0
negative

array([False, False,  True,  True,  True, False, False,  True])

In [427]:
neg_pos[negative]

array([-1, -3, -2, -9])

In [428]:
neg_pos[negative] = 0

In [429]:
neg_pos

array([0, 1, 0, 0, 0, 4, 6, 0])

In [430]:
b = np.arange(25).reshape(5,5)

In [431]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [432]:
b[[0,2,3,3],[2,3,1,4]]

array([ 2, 13, 16, 19])

In [433]:
mask = b % 3 == 0
b[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [434]:
b[np.where(b % 3 == 0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [435]:
# Array Broadcasting
# NumPy arrays of diffrent dimensionality can be combined in the same expression.
# Arrays with smaller dimensions are broadcasted to match larger arrays without copying data

In [436]:
a = np.array([[0],[10],[20],[30]])

In [437]:
b = np.array([0,1,2])

In [438]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [439]:
b

array([0, 1, 2])

In [440]:
y = a + b

In [441]:
y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [442]:
# Broadcasting has two rules

In [443]:
# Rule1 : Prepend ones to smaller array's shape
a = np.ones((3,5)) # a.shape (3,5)
b = np.ones((5,))  # b.shape(5,)
b.reshape((1,5))   # result is a (1,5) shaped array.
b [np.newaxis :]   # equivalant and more consice

array([1., 1., 1., 1., 1.])

In [444]:
b.shape

(5,)

In [445]:
# Rule2: Dimensions of size 1 are repeated without copying.
c = a+b

In [446]:
c.shape

(3, 5)

In [447]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [448]:
b

array([1., 1., 1., 1., 1.])

In [449]:
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [450]:
# Computations with Arrays

In [451]:
# Sum method

In [452]:
# .sum() defaults to adding up all the values in the array
a = np.array([[1,2,3], [4,5,6]])
a.sum()

21

In [453]:
a.sum(axis=0)# Sum along the 0th axis

array([5, 7, 9])

In [454]:
a.sum(axis=1) # sum along the 1st axis

array([ 6, 15])

In [455]:
# MIN/MAX

In [456]:
a = np.array([[5,2], [1,6]])

In [457]:
a.min()

1

In [458]:
a.max()

6

In [459]:
# Use the axis keyword to find
# max values for one dimension
a.max(axis=0)

array([5, 6])

In [460]:
a.min(axis=1)

array([2, 1])

In [463]:
# ARGMIN/MAX
# Many tasks (like optimization)
# are interested in the location 
# of a min/max, not the value
a.argmax()

3

In [468]:
# NOTE:
# arg methods return the
# location in 1D, on a raveled # index of the original array
# NumPy includes a function # to un-flatten 1D locations:
index = np.unravel_index(a.argmax(), a.shape)

In [469]:
a[index]

6