In [2]:
# Importing numpy
import numpy as np

In [ ]:

# Introducing NumPy Arrays


In [3]:
# Simple array creation
a = np.array([0,1,2,3,4])

In [4]:
# Cheking the type
type(a)

numpy.ndarray

In [6]:
# Numeric 'type' of elements
a.dtype

dtype('int64')

In [7]:
# Number of dimentions
a.ndim

1

In [11]:
# Array shape
#  Shape returns a tuple
# listing the length of the
# array along each dimension.

a.shape

(5,)

In [12]:
# Get the number of elements in the array
a.size

5

In [9]:
# Bytes per elements.
a.itemsize

8

In [10]:
# Bytes of memory used
# Return the number of bytes
# used by the data portion of
# the array.

# a has 5 items each takes 8 bytes -> 40.

a.nbytes

40

In [14]:

# Array Operations


In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [16]:
# Addition
a + b

array([3, 5, 7, 9])

In [17]:
# Subtraction
a - b

array([-1, -1, -1, -1])

In [18]:
# Multiplication
a * b

array([ 2,  6, 12, 20])

In [19]:
# Division
a / b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [20]:
# Power
a ** b

array([   1,    8,   81, 1024])

In [21]:
 # Math functions

In [23]:
# create array from 0. to 10.
x = np.arange(11.)

In [24]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# multiply entire array by 
# scalar value
c = (2 * np.pi) / 10.

In [26]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [27]:
# in-place operations
x *= c

In [28]:
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [29]:
# apply functions to array
np.sin(x)

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

In [30]:
# Setting Array Elements.

In [31]:
# Array indexing
a[0]

1

In [32]:
a

array([1, 2, 3, 4])

In [33]:
# assigning a float into
# an int32 array truncates
# the decimal part
a[0] = 10.6

In [34]:
a

array([10,  2,  3,  4])

In [35]:
# fill has the same behavior
a.fill(-4.8)

In [36]:
a

array([-4, -4, -4, -4])

In [37]:
# Multi-Dimentional Arrays 

In [38]:
arr_2d = np.array([[0,1,2,3], [10,11,12,14]])

In [39]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 14]])

In [40]:
arr_2d.shape

(2, 4)

In [43]:
 # Element count
arr_2d.size

8

In [44]:
# Number of dimentions
arr_2d.ndim

2

In [45]:
# Get, Set Elements
arr_2d[0, 0] # get the first item of the first array

0

In [46]:
arr_2d[1,2] # get the third item of the second array
# NOTE : Numpy has 0 indexed arrays.

12

In [47]:
arr_2d[1, 3] = -1

In [48]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [50]:
arr_2d[1] # Get all the elements of the second array

array([10, 11, 12, -1])

In [51]:

# Indexing and Slicing


In [52]:
# Slicing
# var[lower:upper:step]
a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [53]:
a[1:-2] # Negative indices work also

array([11, 12])

In [54]:
a[-4:3]

array([11, 12])

In [55]:
# omitted boundaries are
# assumed to be the beginning
# (or end) of the list

In [56]:
a[:3] # Grab first 3 elements

array([10, 11, 12])

In [58]:
a[-2:] # Grab last 2 elements

array([13, 14])

In [59]:
a[::2] # every other element

array([10, 12, 14])

In [60]:
# Array Slicin'
# Slicing works much like
# standard python slicing.

In [71]:
a = np.array([
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
])
a[0,3:5] # First row column 3->5 (5 not included.)

array([3, 4])

In [66]:
a[2:, 4:] # Get all rows starting from row 2 and all columns starting
          # from the fourth column

array([[24, 25],
       [34, 35]])

In [69]:
a[:, 2] # All rows of column number 2.

array([ 2, 12, 22, 32])

In [72]:
a[2::2, ::2] # Strided are also possible

array([[20, 22, 24],
       [40, 42, 44]])

In [73]:
# Slices are references to locations in memory
# These memory locations can be used in assignment operations.

In [78]:
a = np.array([0, 1, 2, 3, 4])
# slicing the last two elements returns the data there
a[-2:]
a

array([0, 1, 2, 3, 4])

In [77]:
  # we can insert an iterable of length two
a[-2:] = [-10, -20]
a

array([  0,   1,   2, -10, -20])