In [1]:
import numpy as np

In [2]:
# Create a numpy array -> Rank 1 array
a = np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# Get the shape of the array
print(a.shape)

(4,)


In [4]:
print(a[0], a[1], a[2], a[3])

1 2 3 4


In [5]:
# Change the value of the first element
a[0] = 5

In [6]:
print(a)

[5 2 3 4]


In [7]:
b = np.array([[1,2,3,4], [5,6,7,8]])

In [8]:
print(b.shape)

(2, 4)


In [9]:
print(b[0,0])

1


5


In [11]:
print(b[0,-1])

4


In [12]:
print(b[0,1], b[1,0])

2 5


In [13]:
#Create an array of all zeros
c = np.zeros((2,2))

In [14]:
print(c)

[[0. 0.]
 [0. 0.]]


In [15]:
b = np.ones((1,2))    # Create an array of all ones

In [16]:
print(b)

[[1. 1.]]


In [17]:
# Create a constant array filled with 7
d = np.full((2,3), 7)

In [18]:
print(d)

[[7 7 7]
 [7 7 7]]


In [19]:
# Create a 2x2 identity matrix
identity_matrix1 = np.eye(2)
print(identity_matrix1)

[[1. 0.]
 [0. 1.]]


In [20]:
# Create a 4x4 identity matrix
identity_matrix2 = np.eye(4)
print(identity_matrix2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Create an array 2x2 filled with random values
e = np.random.random((2,2))
print(e)

[[0.14599445 0.9647461 ]
 [0.96894661 0.62238719]]
