In [470]:
# Importing numpy
import numpy as np

In [471]:

# Introducing NumPy Arrays


In [472]:
# Simple array creation
a = np.array([0,1,2,3,4])

In [473]:
# Cheking the type
type(a)

numpy.ndarray

In [474]:
# Numeric 'type' of elements
a.dtype

dtype('int64')

In [475]:
# Number of dimentions
a.ndim

1

In [476]:
# Array shape
#  Shape returns a tuple
# listing the length of the
# array along each dimension.

a.shape

(5,)

In [477]:
# Get the number of elements in the array
a.size

5

In [478]:
# Bytes per elements.
a.itemsize

8

In [479]:
# Bytes of memory used
# Return the number of bytes
# used by the data portion of
# the array.

# a has 5 items each takes 8 bytes -> 40.

a.nbytes

40

In [480]:

# Array Operations


In [481]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [482]:
# Addition
a + b

array([3, 5, 7, 9])

In [483]:
# Subtraction
a - b

array([-1, -1, -1, -1])

In [484]:
# Multiplication
a * b

array([ 2,  6, 12, 20])

In [485]:
# Division
a / b

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [486]:
# Power
a ** b

array([   1,    8,   81, 1024])

In [487]:
 # Math functions

In [488]:
# create array from 0. to 10.
x = np.arange(11.)

In [489]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [490]:
# multiply entire array by 
# scalar value
c = (2 * np.pi) / 10.

In [491]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [492]:
# in-place operations
x *= c

In [493]:
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [494]:
# apply functions to array
np.sin(x)

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

In [495]:
# Setting Array Elements.

In [496]:
# Array indexing
a[0]

1

In [497]:
a

array([1, 2, 3, 4])

In [498]:
# assigning a float into
# an int32 array truncates
# the decimal part
a[0] = 10.6

In [499]:
a

array([10,  2,  3,  4])

In [500]:
# fill has the same behavior
a.fill(-4.8)

In [501]:
a

array([-4, -4, -4, -4])

In [502]:
# Multi-Dimentional Arrays 

In [503]:
arr_2d = np.array([[0,1,2,3], [10,11,12,14]])

In [504]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 14]])

In [505]:
arr_2d.shape

(2, 4)

In [506]:
 # Element count
arr_2d.size

8

In [507]:
# Number of dimentions
arr_2d.ndim

2

In [508]:
# Get, Set Elements
arr_2d[0, 0] # get the first item of the first array

0

In [509]:
arr_2d[1,2] # get the third item of the second array
# NOTE : Numpy has 0 indexed arrays.

12

In [510]:
arr_2d[1, 3] = -1

In [511]:
arr_2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [512]:
arr_2d[1] # Get all the elements of the second array

array([10, 11, 12, -1])

In [513]:

# Indexing and Slicing


In [514]:
# Slicing
# var[lower:upper:step]
a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [515]:
a[1:-2] # Negative indices work also

array([11, 12])

In [516]:
a[-4:3]

array([11, 12])

In [517]:
# omitted boundaries are
# assumed to be the beginning
# (or end) of the list

In [518]:
a[:3] # Grab first 3 elements

array([10, 11, 12])

In [519]:
a[-2:] # Grab last 2 elements

array([13, 14])

In [520]:
a[::2] # every other element

array([10, 12, 14])

In [521]:
# Array Slicin'
# Slicing works much like
# standard python slicing.

In [522]:
a = np.array([
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
])
a[0,3:5] # First row column 3->5 (5 not included.)

array([3, 4])

In [523]:
a[2:, 4:] # Get all rows starting from row 2 and all columns starting
          # from the fourth column

array([[24, 25],
       [34, 35],
       [44, 45]])

In [524]:
a[:, 2] # All rows of column number 2.

array([ 2, 12, 22, 32, 42])

In [525]:
a[2::2, ::2] # Strided are also possible

array([[20, 22, 24],
       [40, 42, 44]])

In [526]:
# Slices are references to locations in memory
# These memory locations can be used in assignment operations.

In [527]:
a = np.array([0, 1, 2, 3, 4])
# slicing the last two elements returns the data there
a[-2:]
a

array([0, 1, 2, 3, 4])

In [528]:
  # we can insert an iterable of length two
a[-2:] = [-10, -20] # This is valid if they have the same length.
a

array([  0,   1,   2, -10, -20])

In [529]:
# or a scalar value
a[-2:] = 99
a

array([ 0,  1,  2, 99, 99])

In [530]:
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [531]:
c[-1]# get last row

array([20, 21, 22, 23, 24])

In [532]:
c[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [533]:
c[1::2, :-1:2]

array([[ 5,  7],
       [15, 17]])

In [534]:
# If you wanna make a copy use copy()
d = c.copy()
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [535]:
d [0, 1] = -10
d

array([[  0, -10,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [536]:
c # C is unchanged.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [537]:
# Fancy Indexing

In [538]:
# Indexing by position.
a = np.arange(0, 80, 10)

In [539]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [540]:
y = a[[1,2,-3]] # Fancy indexing.

In [541]:
y

array([10, 20, 50])

In [542]:
# This also work with setting.
a[[1,2,-3]] = 90

In [543]:
a

array([ 0, 90, 90, 30, 40, 90, 60, 70])

In [544]:
# Indexing by booleans
mask = np.array([1,0,1,0,0,0,1,0], dtype=bool)

In [545]:
y = a[mask]# Fancy Indexing 

In [546]:
y

array([ 0, 90, 60])

In [547]:
neg_pos = np.array([0,1,-1,-3,-2,4,6,-9])

In [548]:
negative = neg_pos < 0
negative

array([False, False,  True,  True,  True, False, False,  True])

In [549]:
neg_pos[negative]

array([-1, -3, -2, -9])

In [550]:
neg_pos[negative] = 0

In [551]:
neg_pos

array([0, 1, 0, 0, 0, 4, 6, 0])

In [552]:
b = np.arange(25).reshape(5,5)

In [553]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [554]:
b[[0,2,3,3],[2,3,1,4]]

array([ 2, 13, 16, 19])

In [555]:
mask = b % 3 == 0
b[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [556]:
b[np.where(b % 3 == 0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [557]:
# Array Broadcasting
# NumPy arrays of diffrent dimensionality can be combined in the same expression.
# Arrays with smaller dimensions are broadcasted to match larger arrays without copying data

In [558]:
a = np.array([[0],[10],[20],[30]])

In [559]:
b = np.array([0,1,2])

In [560]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [561]:
b

array([0, 1, 2])

In [562]:
y = a + b

In [563]:
y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [564]:
# Broadcasting has two rules

In [565]:
# Rule1 : Prepend ones to smaller array's shape
a = np.ones((3,5)) # a.shape (3,5)
b = np.ones((5,))  # b.shape(5,)
b.reshape((1,5))   # result is a (1,5) shaped array.
b [np.newaxis :]   # equivalant and more consice

array([1., 1., 1., 1., 1.])

In [566]:
b.shape

(5,)

In [567]:
# Rule2: Dimensions of size 1 are repeated without copying.
c = a+b

In [568]:
c.shape

(3, 5)

In [569]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [570]:
b

array([1., 1., 1., 1., 1.])

In [571]:
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [572]:
# Computations with Arrays

In [573]:
# Sum method

In [574]:
# .sum() defaults to adding up all the values in the array
a = np.array([[1,2,3], [4,5,6]])
a.sum()

21

In [575]:
a.sum(axis=0)# Sum along the 0th axis

array([5, 7, 9])

In [576]:
a.sum(axis=1) # sum along the 1st axis

array([ 6, 15])

In [577]:
# MIN/MAX

In [578]:
a = np.array([[5,2], [1,6]])

In [579]:
a.min()

1

In [580]:
a.max()

6

In [581]:
# Use the axis keyword to find
# max values for one dimension
a.max(axis=0)

array([5, 6])

In [582]:
a.min(axis=1)

array([2, 1])

In [583]:
# ARGMIN/MAX
# Many tasks (like optimization)
# are interested in the location 
# of a min/max, not the value
a.argmax()

3

In [584]:
# NOTE:
# arg methods return the
# location in 1D, on a raveled # index of the original array
# NumPy includes a function # to un-flatten 1D locations:
index = np.unravel_index(a.argmax(), a.shape)

In [585]:
a[index]

6

In [586]:
# EX

In [587]:
from numpy import loadtxt

In [589]:
data = loadtxt('wind.data')

In [608]:
dates = data[:, 0:3]
winds = data[:, 3:]
winds

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

In [601]:
#1

# Calculate the min
print("min: " ,data.min())
# Calculate the max
print("max:" ,data.max())
# Calculate the mean
print("mean: " ,data.mean())
#calculate the std
print("std: " ,data.std())

min:  0.0
max: 78.0
mean:  14.299512726903965
std:  15.91981080866919


In [617]:
#2

# Calculate the min
print("min: " ,winds.min(axis=0))
# Calculate the max
print("max:" ,winds.max(axis=0))
# Calculate the mean
print("mean: " ,winds.mean(axis=0))
#calculate the std
print("std: " ,winds.std(axis=0))

min:  (12,)
max: [35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
mean:  [12.36371463 10.64644813 11.66010344  6.30627472 10.45688013  7.09225434
  9.7968345   8.49442044  8.49581838  8.70726803 13.121007   15.59946152]
std:  [5.61918301 5.26820081 5.00738377 3.60513309 4.93536333 3.96838126
 4.97689374 4.49865783 4.16746101 4.50327222 5.83459319 6.69734719]


In [612]:
test = data[:2]

In [613]:
test

array([[61.  ,  1.  ,  1.  , 15.04, 14.96, 13.17,  9.29, 13.96,  9.87,
        13.67, 10.25, 10.83, 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , 14.71, 16.88, 10.83,  6.5 , 12.62,  7.67,
        11.5 , 10.04,  9.79,  9.67, 17.54, 13.83]])

In [614]:
test.min(axis=0)

array([61.  ,  1.  ,  1.  , 14.71, 14.96, 10.83,  6.5 , 12.62,  7.67,
       11.5 , 10.04,  9.79,  9.67, 17.54, 13.83])