In [149]:
import numpy as np

In [150]:
# Creating ndarrays

In [151]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [152]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [153]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 2D list.
arr2 = np.array(data2)

In [154]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
arr2.ndim # Get the dimentions of the array

2

In [156]:
arr2.shape # Get the shape of the array

(2, 4)

In [157]:
arr1.dtype # Get the data type of the array elements

dtype('float64')

In [158]:
arr2.dtype

dtype('int64')

In [159]:
# Create an arry filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [160]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [161]:
# Create uninitialized array
# NOTE: It’s not safe to assume that np.empty will return an array of all zeros.
# In some cases, it may return uninitialized “garbage” values.
np.empty((2, 3, 2))

array([[[5., 5.],
        [5., 5.],
        [3., 3.]],

       [[3., 3.],
        [1., 1.],
        [1., 1.]]])

In [162]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [163]:
# Data Types for ndarrays

In [164]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [165]:
arr1.dtype

dtype('float64')

In [166]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [167]:
# You can explicitly convert or cast an array from one dtype to another
# using ndarray’s astype method:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [168]:
float_arr = arr.astype(np.float64)

In [169]:
float_arr.dtype

dtype('float64')

In [170]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [171]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [172]:
# If you have an array of strings representing numbers,
# you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [173]:
numeric_strings.astype(np.float64)
# NOTE: Calling astype always creates a new array (a copy of the data), even
# if the new dtype is the same as the old dtype.

array([ 1.25, -9.6 , 42.  ])

In [174]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [175]:
# Arithmetic with NumPy Arrays

In [176]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [177]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [178]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [179]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [180]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [181]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [182]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [183]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [184]:
arr1 > arr2

array([[ True, False,  True],
       [False, False, False]])

In [185]:
# Basic Indexing and Slicing

In [186]:
arr = np.arange(10)

In [187]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
# Get elem at index 5
arr[5]

5

In [189]:
arr[5:8]

array([5, 6, 7])

In [190]:
arr[5:8] = 12 # Assigning to a slice.

In [191]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [192]:
# NOTE: array slices are views on the original array.
# This means that the data is not copied, and any modifications
# to the view will be reflected in the source array.
arr_slice = arr[5:8]

In [193]:
arr_slice

array([12, 12, 12])

In [194]:
arr_slice[1] = 12345

In [195]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [196]:
# The “bare” slice [:] will assign to all values in an array:
arr_slice[:] = -1

In [197]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [198]:
# If you want a copy of a slice of an ndarray instead of a view
# you will need to explicitly copy the array—for example:
arr_slice = arr[5:8].copy()
arr_slice

array([-1, -1, -1])

In [199]:
arr_slice[:] = 123
arr_slice

array([123, 123, 123])

In [200]:
# arr is not affected.
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [201]:
# Working with 2d arrays

In [202]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [203]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
# In a two-dimensional array, the elements at each index
# are no longer scalars but rather one-dimensional arrays:
arr2d[2]

array([7, 8, 9])

In [205]:
arr2d[0][2]

3

In [206]:
arr2d[0, 2]

3

In [207]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [208]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [209]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()

In [211]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
arr3d[0] = 42

In [213]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [214]:
arr3d[0] = old_values

In [215]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [216]:
arr3d[1, 0] # gives you all of the values whose indices start with (1, 0),
            # forming a 1-dimensional array

array([7, 8, 9])

In [217]:
# Indexing with slices

In [218]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [219]:
# Like one-dimensional objects such as Python lists,
# ndarrays can be sliced with the familiar syntax:
arr[1:6]

array([ 1,  2,  3,  4, -1])

In [220]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [221]:
arr2d.ndim

2

In [222]:
arr2d[:2] # get the first 1d arrays. in other words “select the first two rows of arr2d.”

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
# You can pass multiple slices just like you can pass multiple indexes:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [224]:
# When slicing like this, you always obtain array views of the same number of dimensions.
# By mixing integer indexes and slices, you get lower dimensional slices.
arr2d[1, :2]

array([4, 5])

In [225]:
arr2d[:2, 2]

array([3, 6])

In [226]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [227]:
# Of course, assigning to a slice expression assigns to the whole selection:
arr2d[:2, 1:] = 0

In [228]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [229]:
# Boolean Indexing

In [230]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [231]:
data = np.random.randn(7, 4)

In [232]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [233]:
data

array([[ 0.59970234, -0.64269456,  1.38985733,  0.38891895],
       [ 1.10977451, -1.67574593,  1.45512418,  0.15296937],
       [ 0.37280591, -0.26292822,  0.66881107,  0.17762145],
       [-1.48501731,  0.83656416,  0.92571649, -0.55248406],
       [ 0.16876673,  0.24902391,  1.2076048 , -1.18936616],
       [-0.94621104, -0.0783264 ,  0.70123998,  0.39435446],
       [-2.58005394, -0.6281617 , -0.53538614, -0.43229451]])

In [234]:
# Suppose each name corresponds to a row in the data array
# and we wanted to select all the rows with corresponding name 'Bob'.
# Like arithmetic operations, compari‐ sons (such as ==) with arrays are also vectorized.
# Thus, comparing names with the string 'Bob' yields a boolean array
names == 'Bob' # Returns an array with either true or false.

array([ True, False, False,  True, False, False, False])

In [235]:
data[names == 'Bob']

array([[ 0.59970234, -0.64269456,  1.38985733,  0.38891895],
       [-1.48501731,  0.83656416,  0.92571649, -0.55248406]])

In [236]:
data[names == 'Bob', 2:]

array([[ 1.38985733,  0.38891895],
       [ 0.92571649, -0.55248406]])

In [237]:
data[names == 'Bob', 3]

array([ 0.38891895, -0.55248406])

In [238]:
# To select everything but 'Bob', you can either use != or negate the condition using ~:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [239]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [240]:
data[~(names == 'Bob')]

array([[ 1.10977451, -1.67574593,  1.45512418,  0.15296937],
       [ 0.37280591, -0.26292822,  0.66881107,  0.17762145],
       [ 0.16876673,  0.24902391,  1.2076048 , -1.18936616],
       [-0.94621104, -0.0783264 ,  0.70123998,  0.39435446],
       [-2.58005394, -0.6281617 , -0.53538614, -0.43229451]])

In [241]:
data[(names != 'Bob')]

array([[ 1.10977451, -1.67574593,  1.45512418,  0.15296937],
       [ 0.37280591, -0.26292822,  0.66881107,  0.17762145],
       [ 0.16876673,  0.24902391,  1.2076048 , -1.18936616],
       [-0.94621104, -0.0783264 ,  0.70123998,  0.39435446],
       [-2.58005394, -0.6281617 , -0.53538614, -0.43229451]])

In [242]:
# The ~ operator can be useful when you want to invert a general condition:
cond = names == 'Bob'
data[~cond]

array([[ 1.10977451, -1.67574593,  1.45512418,  0.15296937],
       [ 0.37280591, -0.26292822,  0.66881107,  0.17762145],
       [ 0.16876673,  0.24902391,  1.2076048 , -1.18936616],
       [-0.94621104, -0.0783264 ,  0.70123998,  0.39435446],
       [-2.58005394, -0.6281617 , -0.53538614, -0.43229451]])

In [243]:
# Selecting two of the three names to combine multiple boolean conditions,
# use boolean arithmetic operators like & (and) and | (or):
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [244]:
data[mask]

array([[ 0.59970234, -0.64269456,  1.38985733,  0.38891895],
       [ 0.37280591, -0.26292822,  0.66881107,  0.17762145],
       [-1.48501731,  0.83656416,  0.92571649, -0.55248406],
       [ 0.16876673,  0.24902391,  1.2076048 , -1.18936616]])

In [245]:
# NOTE: 
# Selecting data from an array by boolean indexing
# always creates a copy of the data, even if the returned array is unchanged.

In [246]:
# NOTE:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.

In [247]:
# Setting values with boolean arrays works in a common-sense way.
# To set all of the negative values in data to 0 we need only do:
data[data < 0] = 0

In [248]:
data

array([[0.59970234, 0.        , 1.38985733, 0.38891895],
       [1.10977451, 0.        , 1.45512418, 0.15296937],
       [0.37280591, 0.        , 0.66881107, 0.17762145],
       [0.        , 0.83656416, 0.92571649, 0.        ],
       [0.16876673, 0.24902391, 1.2076048 , 0.        ],
       [0.        , 0.        , 0.70123998, 0.39435446],
       [0.        , 0.        , 0.        , 0.        ]])

In [249]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [250]:
# Setting whole rows or columns using a one-dimensional boolean array is also easy:
data[names != 'Joe',1:3] = 7

In [251]:
data

array([[0.59970234, 7.        , 7.        , 0.38891895],
       [1.10977451, 0.        , 1.45512418, 0.15296937],
       [0.37280591, 7.        , 7.        , 0.17762145],
       [0.        , 7.        , 7.        , 0.        ],
       [0.16876673, 7.        , 7.        , 0.        ],
       [0.        , 0.        , 0.70123998, 0.39435446],
       [0.        , 0.        , 0.        , 0.        ]])

In [252]:
# Fancy Indexing
# ==> Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [253]:
arr = np.empty((8, 4)) # 8x4 Array

In [254]:
for i in range(8):
    arr[i] = i

In [255]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [256]:
# To select out a subset of the rows in a particular order,
# you can simply pass a list or ndarray of integers specifying the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [257]:
# Negative indices work also.
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [258]:
arr = np.arange(32).reshape((8, 4))

In [259]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [260]:
# Passing multiple index arrays does something slightly different; it selects a one-
# dimensional array of elements corresponding to each tuple of indices:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [261]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # Very fancy isnt't it @@.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [262]:
# NOTE:
# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.

In [263]:
# Transposing Arrays and Swapping Axes

In [264]:
arr = np.arange(15).reshape((3, 5))

In [265]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [266]:
arr.T # Get the transposing array.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [267]:
arr = np.random.randn(6, 3)

In [268]:
arr

array([[ 4.58438275e-01,  2.06280737e-02, -3.02473379e-01],
       [-4.39921444e-01, -8.61366995e-01,  1.64505059e+00],
       [-5.99153438e-01,  1.96615186e+00, -1.65051875e-03],
       [-4.90002822e-01,  1.42030542e+00, -8.33455198e-01],
       [-4.82822082e-01,  1.57865218e-01,  1.27069923e+00],
       [-2.74822524e-01, -3.02877672e-01, -8.87545139e-01]])

In [269]:
arr = np.arange(16).reshape((2,2,4))

In [270]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [271]:
new_arr = arr.swapaxes(1,2)

In [272]:
new_arr

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [273]:
new_arr.shape

(2, 4, 2)

In [274]:
# Universal Functions: Fast Element-Wise Array Functions
# A universal function, or ufunc, is a function that performs element-wise operations on data
# in ndarrays. You can think of them as fast vectorized wrappers for simple functions
# that take one or more scalar values and produce one or more scalar results.

In [275]:
arr = np.arange(10)

In [276]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
np.sqrt(arr) # Get the square root of every element in the array.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [278]:
np.exp(arr) # Exponent all array elements

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [279]:
x = np.random.randn(8)
y = np.random.randn(8)

In [280]:
x

array([ 0.32849525,  0.71468797, -1.01645247, -0.48999826, -0.962188  ,
        1.24478527, -0.09065637, -0.28761026])

In [281]:
y

array([ 1.31914775, -0.66759708, -1.03387834,  0.51585975,  0.35102397,
        1.18745249,  1.99829149,  0.38007921])

In [282]:
# numpy.maximum will compute the element-wise maximum of the elements in x and y.
np.maximum(x, y) # take two arrays (thus, binary ufuncs)
# and return a single array as the result.

array([ 1.31914775,  0.71468797, -1.01645247,  0.51585975,  0.35102397,
        1.24478527,  1.99829149,  0.38007921])

In [283]:
arr = np.random.randn(7) * 5

In [284]:
arr

array([ 5.95986743, -6.96328183, -6.50990203, -0.92778626, -2.36315206,
        0.17337593, -2.34910822])

In [285]:
remainder, whole_part = np.modf(arr) # returns the fractional and integral parts of a floating-point array

In [286]:
remainder

array([ 0.95986743, -0.96328183, -0.50990203, -0.92778626, -0.36315206,
        0.17337593, -0.34910822])

In [287]:
whole_part

array([ 5., -6., -6., -0., -2.,  0., -2.])

In [288]:
# NOTE: Ufuncs accept an optional out argument that allows them to operate in-place on arrays:
np.sqrt(arr, arr)

<ipython-input-288-10bd82bfa4a8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([2.44128397,        nan,        nan,        nan,        nan,
       0.41638436,        nan])

In [289]:
arr

array([2.44128397,        nan,        nan,        nan,        nan,
       0.41638436,        nan])

In [290]:
# Array-Oriented Programming with Arrays

In [291]:
 points = np.arange(-5, 5, 0.01)

In [292]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      