In [116]:
import numpy as np

In [117]:
# Creating ndarrays

In [118]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [119]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [120]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 2D list.
arr2 = np.array(data2)

In [121]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
arr2.ndim # Get the dimentions of the array

2

In [123]:
arr2.shape # Get the shape of the array

(2, 4)

In [124]:
arr1.dtype # Get the data type of the array elements

dtype('float64')

In [125]:
arr2.dtype

dtype('int64')

In [126]:
# Create an arry filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [128]:
# Create uninitialized array
# NOTE: It’s not safe to assume that np.empty will return an array of all zeros.
# In some cases, it may return uninitialized “garbage” values.
np.empty((2, 3, 2))

array([[[-1.28822975e-231, -1.28822975e-231],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 6.93468224e-310,  3.76231868e+174]],

       [[ 5.59151984e-091,  1.10592089e-046],
        [ 1.28392725e+160,  2.65200039e-032],
        [ 3.99910963e+252,  8.34402701e-309]]])

In [129]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [130]:
# Data Types for ndarrays

In [131]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [132]:
arr1.dtype

dtype('float64')

In [133]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [134]:
# You can explicitly convert or cast an array from one dtype to another
# using ndarray’s astype method:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [135]:
float_arr = arr.astype(np.float64)

In [136]:
float_arr.dtype

dtype('float64')

In [137]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [138]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [139]:
# If you have an array of strings representing numbers,
# you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [140]:
numeric_strings.astype(np.float64)
# NOTE: Calling astype always creates a new array (a copy of the data), even
# if the new dtype is the same as the old dtype.

array([ 1.25, -9.6 , 42.  ])

In [141]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [142]:
# Arithmetic with NumPy Arrays

In [143]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [144]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [145]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [146]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [148]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [149]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [150]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [151]:
arr1 > arr2

array([[ True, False,  True],
       [False, False, False]])

In [152]:
# Basic Indexing and Slicing

In [153]:
arr = np.arange(10)

In [154]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
# Get elem at index 5
arr[5]

5

In [156]:
arr[5:8]

array([5, 6, 7])

In [157]:
arr[5:8] = 12 # Assigning to a slice.

In [158]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [159]:
# NOTE: array slices are views on the original array.
# This means that the data is not copied, and any modifications
# to the view will be reflected in the source array.
arr_slice = arr[5:8]

In [160]:
arr_slice

array([12, 12, 12])

In [161]:
arr_slice[1] = 12345

In [162]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [163]:
# The “bare” slice [:] will assign to all values in an array:
arr_slice[:] = -1

In [164]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [165]:
# If you want a copy of a slice of an ndarray instead of a view
# you will need to explicitly copy the array—for example:
arr_slice = arr[5:8].copy()
arr_slice

array([-1, -1, -1])

In [166]:
arr_slice[:] = 123
arr_slice

array([123, 123, 123])

In [167]:
# arr is not affected.
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [168]:
# Working with 2d arrays

In [169]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [170]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
# In a two-dimensional array, the elements at each index
# are no longer scalars but rather one-dimensional arrays:
arr2d[2]

array([7, 8, 9])

In [172]:
arr2d[0][2]

3

In [173]:
arr2d[0, 2]

3

In [174]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [175]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [176]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()

In [178]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
arr3d[0] = 42

In [180]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [181]:
arr3d[0] = old_values

In [182]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [183]:
arr3d[1, 0] # gives you all of the values whose indices start with (1, 0),
            # forming a 1-dimensional array

array([7, 8, 9])

In [184]:
# Indexing with slices

In [185]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [186]:
# Like one-dimensional objects such as Python lists,
# ndarrays can be sliced with the familiar syntax:
arr[1:6]

array([ 1,  2,  3,  4, -1])

In [187]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
arr2d.ndim

2

In [189]:
arr2d[:2] # get the first 1d arrays. in other words “select the first two rows of arr2d.”

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
# You can pass multiple slices just like you can pass multiple indexes:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [191]:
# When slicing like this, you always obtain array views of the same number of dimensions.
# By mixing integer indexes and slices, you get lower dimensional slices.
arr2d[1, :2]

array([4, 5])

In [192]:
arr2d[:2, 2]

array([3, 6])

In [193]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [194]:
# Of course, assigning to a slice expression assigns to the whole selection:
arr2d[:2, 1:] = 0

In [195]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [196]:
# Boolean Indexing

In [197]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [198]:
data = np.random.randn(7, 4)

In [199]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [200]:
data

array([[-0.32396115,  0.62476322, -0.47775686,  0.3223527 ],
       [ 1.73582787, -0.37899833, -1.52059523,  0.96194041],
       [ 0.14747179,  1.08194189, -0.55876244,  0.66317473],
       [ 1.0250891 , -0.38732806, -1.81126394, -1.00055277],
       [-0.3423573 ,  0.74819908,  0.48871141, -0.66008026],
       [ 0.27408582, -0.02496033, -0.0360106 , -0.55044695],
       [-1.35737988, -0.3879293 ,  1.07080798, -1.0542189 ]])

In [201]:
# Suppose each name corresponds to a row in the data array
# and we wanted to select all the rows with corresponding name 'Bob'.
# Like arithmetic operations, compari‐ sons (such as ==) with arrays are also vectorized.
# Thus, comparing names with the string 'Bob' yields a boolean array
names == 'Bob' # Returns an array with either true or false.

array([ True, False, False,  True, False, False, False])

In [202]:
data[names == 'Bob']

array([[-0.32396115,  0.62476322, -0.47775686,  0.3223527 ],
       [ 1.0250891 , -0.38732806, -1.81126394, -1.00055277]])

In [203]:
data[names == 'Bob', 2:]

array([[-0.47775686,  0.3223527 ],
       [-1.81126394, -1.00055277]])

In [204]:
data[names == 'Bob', 3]

array([ 0.3223527 , -1.00055277])

In [205]:
# To select everything but 'Bob', you can either use != or negate the condition using ~:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [206]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [207]:
data[~(names == 'Bob')]

array([[ 1.73582787, -0.37899833, -1.52059523,  0.96194041],
       [ 0.14747179,  1.08194189, -0.55876244,  0.66317473],
       [-0.3423573 ,  0.74819908,  0.48871141, -0.66008026],
       [ 0.27408582, -0.02496033, -0.0360106 , -0.55044695],
       [-1.35737988, -0.3879293 ,  1.07080798, -1.0542189 ]])

In [208]:
data[(names != 'Bob')]

array([[ 1.73582787, -0.37899833, -1.52059523,  0.96194041],
       [ 0.14747179,  1.08194189, -0.55876244,  0.66317473],
       [-0.3423573 ,  0.74819908,  0.48871141, -0.66008026],
       [ 0.27408582, -0.02496033, -0.0360106 , -0.55044695],
       [-1.35737988, -0.3879293 ,  1.07080798, -1.0542189 ]])

In [209]:
# The ~ operator can be useful when you want to invert a general condition:
cond = names == 'Bob'
data[~cond]

array([[ 1.73582787, -0.37899833, -1.52059523,  0.96194041],
       [ 0.14747179,  1.08194189, -0.55876244,  0.66317473],
       [-0.3423573 ,  0.74819908,  0.48871141, -0.66008026],
       [ 0.27408582, -0.02496033, -0.0360106 , -0.55044695],
       [-1.35737988, -0.3879293 ,  1.07080798, -1.0542189 ]])

In [210]:
# Selecting two of the three names to combine multiple boolean conditions,
# use boolean arithmetic operators like & (and) and | (or):
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [211]:
data[mask]

array([[-0.32396115,  0.62476322, -0.47775686,  0.3223527 ],
       [ 0.14747179,  1.08194189, -0.55876244,  0.66317473],
       [ 1.0250891 , -0.38732806, -1.81126394, -1.00055277],
       [-0.3423573 ,  0.74819908,  0.48871141, -0.66008026]])

In [212]:
# NOTE: 
# Selecting data from an array by boolean indexing
# always creates a copy of the data, even if the returned array is unchanged.

In [213]:
# NOTE:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.

In [214]:
# Setting values with boolean arrays works in a common-sense way.
# To set all of the negative values in data to 0 we need only do:
data[data < 0] = 0

In [215]:
data

array([[0.        , 0.62476322, 0.        , 0.3223527 ],
       [1.73582787, 0.        , 0.        , 0.96194041],
       [0.14747179, 1.08194189, 0.        , 0.66317473],
       [1.0250891 , 0.        , 0.        , 0.        ],
       [0.        , 0.74819908, 0.48871141, 0.        ],
       [0.27408582, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.07080798, 0.        ]])

In [216]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [219]:
# Setting whole rows or columns using a one-dimensional boolean array is also easy:
data[names != 'Joe',1:3] = 7

In [220]:
data

array([[0.        , 7.        , 7.        , 7.        ],
       [1.73582787, 0.        , 0.        , 0.96194041],
       [0.14747179, 7.        , 7.        , 7.        ],
       [1.0250891 , 7.        , 7.        , 7.        ],
       [0.        , 7.        , 7.        , 7.        ],
       [0.27408582, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.07080798, 0.        ]])

In [222]:
# Fancy Indexing
# ==> Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [223]:
arr = np.empty((8, 4)) # 8x4 Array

In [224]:
for i in range(8):
    arr[i] = i

In [225]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [226]:
# To select out a subset of the rows in a particular order,
# you can simply pass a list or ndarray of integers specifying the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [227]:
# Negative indices work also.
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [228]:
arr = np.arange(32).reshape((8, 4))

In [229]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [230]:
# Passing multiple index arrays does something slightly different; it selects a one-
# dimensional array of elements corresponding to each tuple of indices:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [231]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # Very fancy isnt't it @@.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [232]:
# NOTE:
# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.

In [233]:
# Transposing Arrays and Swapping Axes

In [234]:
arr = np.arange(15).reshape((3, 5))

In [235]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [236]:
arr.T # Get the transposing array.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])