In [1]:
import numpy as np

In [2]:
# Creating ndarrays

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 2D list.
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim # Get the dimentions of the array

2

In [8]:
arr2.shape # Get the shape of the array

(2, 4)

In [9]:
arr1.dtype # Get the data type of the array elements

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [11]:
# Create an arry filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
# Create uninitialized array
# NOTE: It’s not safe to assume that np.empty will return an array of all zeros.
# In some cases, it may return uninitialized “garbage” values.
np.empty((2, 3, 2))

array([[[-1.28822975e-231, -1.28822975e-231],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 5.74020225e+180,  3.76231868e+174]],

       [[ 5.59151984e-091,  1.10592089e-046],
        [ 1.28392725e+160,  2.65200039e-032],
        [ 3.99910963e+252,  9.03750044e-309]]])

In [14]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# Data Types for ndarrays

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [19]:
# You can explicitly convert or cast an array from one dtype to another
# using ndarray’s astype method:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)

In [21]:
float_arr.dtype

dtype('float64')

In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [23]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
# If you have an array of strings representing numbers,
# you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [25]:
numeric_strings.astype(np.float64)
# NOTE: Calling astype always creates a new array (a copy of the data), even
# if the new dtype is the same as the old dtype.

array([ 1.25, -9.6 , 42.  ])

In [26]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [27]:
# Arithmetic with NumPy Arrays

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [29]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [35]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [36]:
arr1 > arr2

array([[ True, False,  True],
       [False, False, False]])

In [37]:
# Basic Indexing and Slicing

In [38]:
arr = np.arange(10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# Get elem at index 5
arr[5]

5

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8] = 12 # Assigning to a slice.

In [43]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
# NOTE: array slices are views on the original array.
# This means that the data is not copied, and any modifications
# to the view will be reflected in the source array.
arr_slice = arr[5:8]

In [45]:
arr_slice

array([12, 12, 12])

In [46]:
arr_slice[1] = 12345

In [47]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [48]:
# The “bare” slice [:] will assign to all values in an array:
arr_slice[:] = -1

In [49]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [50]:
# If you want a copy of a slice of an ndarray instead of a view
# you will need to explicitly copy the array—for example:
arr_slice = arr[5:8].copy()
arr_slice

array([-1, -1, -1])

In [51]:
arr_slice[:] = 123
arr_slice

array([123, 123, 123])

In [52]:
# arr is not affected.
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [53]:
# Working with 2d arrays

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [55]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# In a two-dimensional array, the elements at each index
# are no longer scalars but rather one-dimensional arrays:
arr2d[2]

array([7, 8, 9])

In [57]:
arr2d[0][2]

3

In [58]:
arr2d[0, 2]

3

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()

In [63]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr3d[0] = 42

In [65]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0] = old_values

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[1, 0] # gives you all of the values whose indices start with (1, 0),
            # forming a 1-dimensional array

array([7, 8, 9])

In [69]:
# Indexing with slices

In [70]:
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [71]:
# Like one-dimensional objects such as Python lists,
# ndarrays can be sliced with the familiar syntax:
arr[1:6]

array([ 1,  2,  3,  4, -1])

In [72]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr2d.ndim

2

In [74]:
arr2d[:2] # get the first 1d arrays. in other words “select the first two rows of arr2d.”

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# You can pass multiple slices just like you can pass multiple indexes:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [77]:
# When slicing like this, you always obtain array views of the same number of dimensions.
# By mixing integer indexes and slices, you get lower dimensional slices.
arr2d[1, :2]

array([4, 5])

In [79]:
arr2d[:2, 2]

array([3, 6])

In [80]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [81]:
# Of course, assigning to a slice expression assigns to the whole selection:
arr2d[:2, 1:] = 0

In [82]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])